# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_pmd_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: pmd
        uses: rtjl/pmd-analyzer-action@v0.1.2-alpha
        with:
          pmd-version: '6.31.0'
          source-path: './src'
          rule-path: './PMD.Rules.xml'
      - run: echo No of violations ${{ steps.pmd.outputs.no-of-violations }}
        shell: bash
